In [1]:
import numpy as np

arr = np.array([10,20,30,40])

print(arr[:3])

[10 20 30]


In [3]:
print(arr[2:3])

[30]


In [9]:
arr2 = np.array([[10,20,30,40],[50,60,70,80]])

print(arr2[0:2,1:3])

[[20 30]
 [60 70]]


In [10]:
print(arr2.shape)

(2, 4)


In [11]:
print(arr2.size)

8


In [13]:
print(arr2.dtype)

int64


In [17]:
b = np.array_split(arr2,2)
print(b)

[array([[10, 20, 30, 40]]), array([[50, 60, 70, 80]])]


In [2]:
# will start with functions on arrays

In [9]:
import numpy as np

arr1D = np.array([1,2,3,4])
arr2D = np.array([[10,20,30,40],[50,60,70,80]])

In [14]:
# append in 1D

print(np.append(arr1D,[50]))
print(np.append(arr1D,[50,70]))

[ 1  2  3  4 50]
[ 1  2  3  4 50 70]


In [19]:
# append in 2D

print(np.append(arr2D,[5]))
print(np.append(arr2D,[5,7]))

[10 20 30 40 50 60 70 80  5]
[10 20 30 40 50 60 70 80  5  7]


In [24]:
# insert in 1D

print(np.insert(arr1D,1,[50]))
print(np.insert(arr1D,1,[50,70]))

[ 1 50  2  3  4]
[ 1 50 70  2  3  4]


In [49]:
# insert in 2D

print(np.insert(arr2D,1,[5]))
print(np.insert(arr2D,1,[5,7]))
print(np.insert(arr2D,1,[5],axis=1))
print(np.insert(arr2D,1,[5],axis=0))
print(np.insert(arr2D,1,[5,7],axis=1))


[10  5 20 30 40 50 60 70 80]
[10  5  7 20 30 40 50 60 70 80]
[[10  5 20 30 40]
 [50  5 60 70 80]]
[[10 20 30 40]
 [ 5  5  5  5]
 [50 60 70 80]]
[[10  5 20 30 40]
 [50  7 60 70 80]]


In [46]:
# delete in 1D

print(np.delete(arr1D,1))
print(np.delete(arr1D,[2,3]))

[1 3 4]
[1 2]


In [47]:
# delete in 2D

print(np.delete(arr2D,1))
print(np.delete(arr2D,[2,3]))

[10 30 40 50 60 70 80]
[10 20 50 60 70 80]


In [50]:
# Search, sort and filter arrays

In [51]:
import numpy as np

arr1D = np.array([2,1,4,3])
arr2D = np.array([[2,1,4,3],[7,6,8,5]])

In [53]:
print(np.sort(arr1D))
print(np.sort(arr2D))

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [63]:
print(np.where(arr1D == 4))
print(np.where(arr2D == 5))

(array([2]),)
(array([1]), array([3]))


In [64]:
print(np.where(arr1D % 2 == 0))
print(np.where(arr2D % 2 == 0))

(array([0, 2]),)
(array([0, 0, 1, 1]), array([0, 2, 1, 2]))


In [68]:
sorted_array= np.array([1,2,3,4,5])
print(np.searchsorted(sorted_array,3))

2


In [72]:
# Filtering of array

arr = np.array([1,3,2,5])
filtered_array = [True, False, True, True]
print(arr[filtered_array])


[1 2 5]


In [73]:
arr = np.array([1,3,2,5])
filtered_array = arr>2
print(arr[filtered_array])

[3 5]


In [74]:
# Aggregating functions in arrays

In [80]:
a = np.array([20,40,60,70])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

190
20
70
4
47.5
[ 20  60 120 190]
[     20     800   48000 3360000]


In [92]:
price = np.array([100,150,199,200,250,130]) 
quantity = np.array([10,50,30,40,30,10])
arr = np.cumprod([price,quantity],axis=0)
print(np.sum(arr[1]))

31270


In [106]:
# statistical functions

import numpy as np
import statistics as stats

baked_food = [200,150,150,130,200,220,170,188]
a = np.array(baked_food)

print(np.mean(a))
print(np.median(a))
print(stats.mode(a))
print(np.std(a))
print(np.var(a))

176.0
179.0
200
29.017236257093817
842.0
